Repository Ecell-NITS/Srigen-2023, pull requests merged in 2023-02, with the labels that each got.

#1 FIX: Template variables
  src/index.scss
Labels: pls-merge

#3 Footer
  package.json
  pnpm-lock.yaml
  public/fonts/gilroy/Gilroy-Black.ttf
  public/fonts/gilroy/Gilroy-BlackItalic.ttf
  public/fonts/gilroy/Gilroy-Bold.ttf
  public/fonts/gilroy/Gilroy-BoldItalic.ttf
  public/fonts/gilroy/Gilroy-ExtraBold.ttf
  public/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
  public/fonts/gilroy/Gilroy-Heavy.ttf
  public/fonts/gilroy/Gilroy-HeavyItalic.ttf
  public/fonts/gilroy/Gilroy-Light.ttf
  public/fonts/gilroy/Gilroy-LightItalic.ttf
  public/fonts/gilroy/Gilroy-Medium.ttf
  public/fonts/gilroy/Gilroy-MediumItalic.ttf
  public/fonts/gilroy/Gilroy-Regular.ttf
  public/fonts/gilroy/Gilroy-RegularItalic.ttf
  public/fonts/gilroy/Gilroy-SemiBold.ttf
  public/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
  public/fonts/gilroy/Gilroy-Thin.ttf
  public/fonts/gilroy/Gilroy-ThinItalic.ttf
  public/fonts/gilroy/Gilroy-UltraLight.ttf
  public/fonts/gilroy/Gilroy-UltraLightItalic.ttf
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.module.scss
  src/Components/index.jsx
  src/index.scss
Labels: wip

#12 Speakers homepage
  package.json
  pnpm-lock.yaml
  public/fonts/.gitkeep
  public/images/.gitkeep
  public/images/speaker-bg.png
  src/Components/Footer/Footer.module.scss
  src/Components/Speaker/Speakers.jsx
  src/Components/Speaker/Speakers.module.scss
  src/Components/index.jsx
  src/Data/Speakers.json
  src/Pages/Home/Home.jsx
  src/index.scss
Labels: pls-merge

#14 ADD: registration page UI
  public/images/Line1.png
  public/images/iplimg.png
  public/images/plussign.png
  src/App.jsx
  src/Components/IndividualRegistrationForm/IndividualForm.module.scss
  src/Components/IndividualRegistrationForm/IndividulalForm.jsx
  src/Components/TeamRegistrationForm/TeamForm.jsx
  src/Components/TeamRegistrationForm/TeamForm.module.scss
  src/Components/index.jsx
  src/Data/Events.json
  src/Pages/Registration/Registration.jsx
  src/Pages/Registration/Registration.module.scss
  src/Pages/index.jsx
  src/index.scss
Labels: pls-merge

#11 ADD: Team Card Component
  public/images/tom.png
  src/Components/TeamCard/TeamCard.jsx
  src/Components/TeamCard/TeamCard.module.scss
  src/Components/index.jsx
  src/index.scss
Labels: pls-merge

#13 About Section
  package.json
  pnpm-lock.yaml
  public/images/about1.png
  public/images/about2.png
  src/Components/About/About.jsx
  src/Components/About/About.module.scss
  src/Components/index.jsx
  src/Pages/Home/Home.jsx
Labels: pls-merge

#22 Sponsors homepage
  src/Components/About/About.jsx
  src/Components/Speaker/Speakers.jsx
  src/Components/Speaker/Speakers.module.scss
  src/Components/Sponsors/Sponsors.jsx
  src/Components/Sponsors/Sponsors.module.scss
  src/Components/index.jsx
  src/Data/Sponsor.json
  src/Pages/Home/Home.jsx
  src/index.scss
Labels: pls-merge

#23 FIX: Issues, ADD: demo register function
  public/db/events.json
  src/Components/TeamRegistrationForm/TeamForm.jsx
  src/Pages/Registration/Registration.jsx
  src/Pages/Registration/Registration.module.scss
Labels: wip

#21 Gallery carousel
  src/App.jsx
  src/Components/GalleryCarousel/GalleryCarousel.jsx
  src/Components/GalleryCarousel/GalleryCarousel.module.scss
  src/Components/index.jsx
  src/Data/GalleryImagesLinks.json
  src/Pages/Home/Home.jsx
  src/index.scss
Labels: wip

#26 Sponsorspage
  public/logos/asus-mini.svg
  public/logos/asus.png
  public/logos/devfolio-mini.svg
  public/logos/devfolio.png
  public/logos/mlh-mini.svg
  public/logos/mlh.png
  public/logos/polygon-mini.svg
  public/logos/polygon.png
  public/logos/wolf-mini.svg
  public/logos/wolf.png
  src/App.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.module.scss
  src/Pages/Sponsors/Sponsors.jsx
  src/Pages/Sponsors/Sponsors.module.scss
  src/Pages/index.jsx
  src/index.scss
Labels: don't merge

#27 ADD: Sidelinks component
  src/Components/Sidelinks/Sidelinks.jsx
  src/Components/Sidelinks/Sidelinks.module.scss
  src/Components/index.jsx
  src/Pages/Registration/Registration.jsx
  src/Pages/Registration/Registration.module.scss
Labels: pls-merge

#28 ADD: Event card
  src/Components/EventCard/EventCard.jsx
  src/Components/EventCard/EventCard.module.scss
  src/Components/index.jsx
  src/Data/EventCardData.json
  src/Pages/Home/Home.jsx
Labels: pls-merge
